name: Continuous integration

on: 
  push:
  pull_request:
    branches: [master]

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        cucumber-version: [7.x, 8.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn install

      - name: Eslint
        run: yarn lint

      - name: Prettier
        run: yarn check-fmt

      - name: Tests
        run: yarn test-cli

      - name: Coverage
        run: yarn test-cover

      - name: Coveralls Parallel
        env:
          COVERALLS_FLAG_NAME: run-${{ matrix.node-version }}-${{ matrix.cucumber-version }}
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel: true

  coverall:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@v1.1.1
        with:
            github-token: ${{ secrets.github_token }}
            parallel-finished: true